- name: Create an ec2 instance
  hosts: localhost
  gather_facts: yes
  tasks:
    - name:
      apt:
        name: python3-pip
    - pip: 
        name: boto

    - name: Launch instance
      ec2:
        aws_access_key: xxxxx
        aws_secret_key: xxxxx
        instance_type: t2.micro
        image: ami-01c592dda54e43c1a 
        region: ca-central-1
